name: Vercel Actions

on: 
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Vercel Actions
        uses: nexterias/actions-vercel@v1.2.3
        with:
          # Vercel token: https://vercel.com/account/tokens
          token: ${{ secrets.VERCEL_TOKEN }} # Replace with your Vercel token
          # Vercel project ID
          project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Replace with your Vercel project ID
          # User ID within Vercel
          org-id: ${{ secrets.VERCEL_ORG_ID }} # Replace with your Vercel org ID
          # Personal Access Token (PAT) is used to create commit status and deployments.
          github-token: ${{ github.token }} # optional, default is ${{ github.token }}
          # Create a production deployment
          production: true # optional, default is false
          # Use the --prebuilt option
          prebuilt: false # optional, default is false
          # Current Working Directory (default: process.cwd())
          cwd: ./ # optional
          # Assign domains (multiple domains can be specified)
          domain-alias: theworldmachine.xyz # optional
          # Name for the target deployment environment
          github-deployment-environment: production # optional
          # Deployment is public (`/_src` is exposed)
          public: true # optional, default is false
